basic_app/urls.py
from django.urls import path
from . import views

# TEMPLATE URLS

app_name= 'basic_app'

urlpatterns = [
    path('', views.index, name ='index'),
    path('home/',views.index, name= 'index'),
    path('register/', views.register, name='register'),
    path('login/', views.user_login, name='user_login'),
    path('logout/', views.user_logout, name='logout'),
    path('special/', views.special, name='special')

]

learning_users/urls.py
from django.contrib import admin
from django.urls import path,include
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('basic_app.urls'), name='index'),
    path('basic_app/', include('basic_app.urls'))
    
]

basic_app/models.py
from django.db import models
from django.contrib.auth.models import User


# Create your models here.

class UserProfileInfo(models.Model):
    user = models.OneToOneField(User,on_delete=models.CASCADE)

    portfolio_site = models.URLField(blank=True)
    profile_pic = models.ImageField(upload_to= 'profile_pics', blank= True)

    def __str__(self):
        return self.user.username

basic_app/forms.py
from django import forms
from django.contrib.auth.models import User
from .models import UserProfileInfo

class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())

    class Meta():
        model = User
        fields = ('username', 'email', 'password')
        
class UserProfileInfoForm(forms.ModelForm):
    class Meta():
        model = UserProfileInfo
        fields = ('portfolio_site', 'profile_pic')

basic_app/views.py
from .forms import UserForm, UserProfileInfoForm
from django.shortcuts import render
from django.contrib.auth import authenticate, login, logout
from django.urls import reverse
from django.http import HttpResponseRedirect, HttpResponse, request
from django.contrib.auth.decorators import login_required

# Create your views here.

def index(request):
    return render(request, 'basic_app/index.html')


@login_required
def special(request):
    return HttpResponse(request, "you are logged in , Nice")

@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('index'))
    # return HttpResponseRedirect(reverse('basic_app:index'))

def register(request):
    registered = False
    
    if request.method == "POST":
        user_form = UserForm(data=request.POST)
        profile_form = UserProfileInfoForm(data=request.POST)

        if user_form.is_valid() and profile_form.is_valid():
            user = user_form.save()
            user.set_password(user.password)
            user.save()

            profile = profile_form.save(commit = False)
            profile.user = user

            if 'profile_pic' in request.FILES:
                profile.profile_pic = request.FILES['profile_pic']

                profile.save()

                registered= True

        else:
            print(user_form.errors,profile_form.errors)

    else:
        user_form = UserForm()
        profile_form = UserProfileInfoForm

    return render(request, 'basic_app/registration.html',
                             {'user_form': user_form,
                             'profile_form': profile_form,
                             'registered':registered})


def user_login(request):
    
    if request.method == 'POST':
    
        username = request.POST.get('username')
        password = request.POST.get('password')   
        user = authenticate(username=username, password=password)      
        if user:        
            if user.is_active:
                
                login(request,user)
                
                return HttpResponseRedirect(reverse('index'))
            else:
                
                return HttpResponse("Your account is not active.")
        else:
            print("Someone tried to login and failed.")
            print("They used username: {} and password: {}".format(username,password))
            return HttpResponse("Invalid login details supplied.")

    else:
       
        return render(request, 'basic_app/login.html', {})

templates/basic_app/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Base</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
</head>
<body>
    <nav class="navbar navbar-default navbar-static-top">
        <div class="container">
            <ul class="nav navbar-nav">
                <li><a class= "navbar-brand" href="{% url 'basic_app:index' %}">Django</a></li>
                <li><a class= "navbar-link" href="{% url 'admin:index' %}">Admin</a></li>
                <li><a class= "navbar-link" href="{% url 'basic_app:register' %}">Register</a></li>
                {% if user.is_authenticated %}
                <li><a class= "navbar-link" href="{% url 'basic_app:logout' %}">Logout</a></li>

                {% else %}
                <li><a class= "navbar-link" href="{% url 'basic_app:user_login' %}">LOGIN HERE</a></li>

                {% endif %}

            </ul>
        </div>

    </nav>
    <div class="container">
        {% block body_block %}
        {% endblock %}

    </div>
    

</body>
</html>

templates/basic_app/index.html
{% extends "basic_app/base.html" %}

{% block body_block %}

<div class="container">
    <div class="jumbotron">
      <h1>Django Level Five</h1>
      {% if user.is_authenticated %}
          <h2>Welcome {{ user.username }}!</h2>
      {% else %}
          <h2>Welcome to the site!</h2>
      {% endif %}
    </div>
  </div>
  
  {% endblock %}

templates/basic_app/login.html
{% extends 'basic_app/base.html' %}
{% block body_block %}
<div class="jumbotron">
    <h1> PLEASE LOGIN </h1>
    <form action="{% url 'basic_app:user_login' %}" method="POST"></form>
    {% csrf_token %}
    <label for="username">Username</label>
    <input type="text" name="username" placeholder="Enter your username">

    <label for="password"> Password </label>
    <input type="password" name="password" >

    <input type="submit" value="LOGIN">
</div>
{% endblock %}

templates/basic_app/registration.html
{% extends 'basic_app/base.html' %}
{% load static %}

{% block body_block %}
<div class="jumbotron">
    {% if registered %}
        <h1>Thank you for registring!!!!!</h1>

    {% else %}
    <h1>Register here </h1>
    <h3>Fill out the form</h3>
    <form  enctype="multipart/form-data" method="POST">
        {% csrf_token %}
        {{ user_form.as_p }}
        {{ profile_form.as_p }}
        <input type="submit" value="Register">
    </form>
    {% endif %}
</div>
{% endblock %}